### ISSUE TITLE
bring PyPI package up to date

### ISSUE THREAD

**Issue by gfairchild** [notanumber/xapian-haystack#114]
Currently, `pip install xapian-haystack` installs version 1.1.5 beta, which is incompatible with Haystack 2.x. However, the readme file here on the GitHub page states that this project works with Haystack 2.x and also lists `pip install xapian-haystack` as one of the methods for installation. This is confusing because in order for xapian-haystack to work with Haystack 2.x, we need to use the code from the master branch here.

The best remedy would be to simply update the PyPI package. Alternatively, remove option in the readme suggesting that `pip install xapian-haystack` will successfully allow Xapian usage under Haystack 2.x.

**Comment by camilonova** [comment]
@jorgecarleitao To avoid confusions can you sync master branch with pypi ?

**Comment by jorgecarleitao** [comment]
I don't have permissions for that, maybe @notanumber has them? I'm trying to have Python 3 support before a new release.

**Comment by notanumber** [comment]
I think I can give @jorgecarleitao permission to do this if had your PyPI username.  Is it the same as your Github username?

**Comment by jorgecarleitao** [comment]
Yes, it is.

**Comment by notanumber** [comment]
Added @jorgecarleitao as a maintainer on PyPI.  Think that'll give you the permission you need.  Let me know if it's not.

**Comment by jorgecarleitao** [comment]
Thanks a lot @notanumber.

**Comment by camilonova** [comment]
Thanks guys.

@jorgecarleitao How much you think is going to take? If is more than two weeks can you issue an smaller release before Python 3 support?
