### ISSUE TITLE
Xapian indexing successfully (I think) but not returning results

### ISSUE THREAD

**Issue by kmgroup** [notanumber/xapian-haystack#158]
I've recently upgraded a site from Django 1.3 to 1.8. I've had Xapian/Haystack search running flawlessly on this site until the upgrade (see current environment below). The Xapian index seems to be building, but I can't return results. Whoosh works fine with this install, btw...but it's spelling  suggestions leave much to be desired, so I really want to get Xapian working again.

---

$ ./manage.py rebuild_index -v3

Indexing 281 products
  indexed 1 - 281 of 281 (by 81978).

$ ./manage.py shell

from haystack.query import SearchQuerySet
sqs = SearchQuerySet().all()
sqs.count()
0

---

Current Environment:
Django 1.8.x
Xapian 1.2.19 (also tried many others including 1.3.x)
Xapian-Haystack 2.0.0
Django-Haystack 2.4.1 (also tried 2.5.dev0)
OSX 10.9.x
Virtualenv/Python 2.7.2

Any ideas?

Thanks!

**Comment by ArturTan** [comment]
I assume that you have found the answer on your question. However, I have solved this issue by introducing xapian.QueryParser() into the XapianSearchQuery.build_query() functions (and provide several little improvements). 

[xapian_backend.txt](https://github.com/notanumber/xapian-haystack/files/1140133/xapian_backend.txt)

You need to change extention of this file to the *.py and change your original xapian_backend.py with it. It should be working.

**Comment by claudep** [comment]
Closing old issues, please reopen if it is still an issue with recent packages.
