### ISSUE TITLE
Release a version compatible with haystack >= 2.5.1

### ISSUE THREAD

**Issue by claudep** [notanumber/xapian-haystack#167]
Hey Jorge, what about a release soon?
Probably 2.1, and we should require haystack 2.5.1.

**Comment by jorgecarleitao** [comment]
I agree, Claude. I will prepare one this weekend, along with the fix of #165.

**Comment by claudep** [comment]
Awesome, thanks!

**Comment by plungerman** [comment]
+1. i am just about to embark upon a django-haystack/xapian project and this would be handy.

**Comment by jorgecarleitao** [comment]
This is a bit delayed, but it is not forgotten. I already have the tests for #165, and I merged everything together. I just need to finish the packing and send submit to pypip.

The version is bumped to 2.1, and requirements will now be
```
Python 2.7 or 3.3
Xapian>=1.2.19
Django>=1.8
Django-Haystack>=2.5.1
```

**Comment by claudep** [comment]
Great, many thanks!
https://pypi.python.org/pypi/xapian-haystack/2.1.0
