### ISSUE TITLE
install xapian error

### ISSUE THREAD

**Issue by robslotboom** [notanumber/xapian-haystack#177]
Running install_xapian.sh 1.4.5 on FreeBSD 10.3-RELEASE-p24 results in the following error:

/usr/bin/ld: cannot find -lstdc++
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[3]: stopped in /usr/home/robert/fabtesta/courgette/1.2/virtualenv/packages/xapian-bindings-1.4.5/python3
*** Error code 1

Stop.
make[2]: stopped in /usr/home/robert/fabtesta/courgette/1.2/virtualenv/packages/xapian-bindings-1.4.5/python3
*** Error code 1

Stop.
make[1]: stopped in /usr/home/robert/fabtesta/courgette/1.2/virtualenv/packages/xapian-bindings-1.4.5
*** Error code 1

Stop.
make: stopped in /usr/home/robert/fabtesta/courgette/1.2/virtualenv/packages/xapian-bindings-1.4.5

Any suggestions?

**Comment by claudep** [comment]
I guess this is more of a xapian issue (maybe solved in the mean time?)

**Comment by robslotboom** [comment]
Years after...

**Comment by claudep** [comment]
Yes, a long sleep for the project :-)
