### ISSUE TITLE
Latest release on pypi.org not reflected in release on github

### ISSUE THREAD

**Issue by dvzrv** [notanumber/xapian-haystack#190]
Hi, I'm packaging python-xapian-haystack for Arch Linux.

The current latest (2.1.1) release on pypi is not reflected in a release in this repository. Could you please add it? Thanks!

**Comment by dvzrv** [comment]
@notanumber can you please respond to this ticket? From the outside it is not possible to understand whether the 2.1.1 release on pypi.org is malicious content or not.
I am unable to upgrade to 2.1.1 because of this

**Comment by notanumber** [comment]
Oh, hey @dvzrv sorry about that. I honestly can't answer this as I haven't been involved with this codebase in years. It's actually being maintained by @jorgecarleitao 

Maybe he can answer? I don't want to step on any toes and I don't have to the code, besides what's on Github, anymore.

**Comment by jorgecarleitao** [comment]
I am also no longer maintaining this code base, as I shifted priorities to other projects.

**Comment by notanumber** [comment]
@jorgecarleitao does the repo on Github have the latest code to match what's on PyPI?

**Comment by dvzrv** [comment]
@notanumber @jorgecarleitao it would be great to get this sorted out, as unmaintained code being used in other projects (e.g. mailman's hyperkitty) is not great either.

Maybe searching for a new maintainer might be a possibility? I'm not sure how large the user-base is :)

**Comment by notanumber** [comment]
I'd be happy to transfer ownership of this project to anyone that'd like to take over maintenance. Unfortunately, I don't have the time to work on it myself.

**Comment by claudep** [comment]
@jorgecarleitao, @notanumber, would it be possible to obtain write permissions on this repo? I cannot guarantee that I will maintain the package in the longer term, but I'd like at least make it work with recent releases of Django.

**Comment by notanumber** [comment]
@claudep absolutely. I'd love to see this repo revived!

**Comment by claudep** [comment]
Awesome, thanks a lot. Would you also be able to migrate the CI from travis.org to travis.com?

**Comment by notanumber** [comment]
I don't think I have access to that, unfortunately. I believe this was @jorgecarleitao that set that up. Let's see if that's something he can help with.

**Comment by claudep** [comment]
Maybe, but considering the CI is under the notanumber path (https://travis-ci.org/notanumber/xapian-haystack/...), I guess you should have editing rights on that part.

**Comment by notanumber** [comment]
Ok. Think I got the migration done. I've never actually used Travis before though, so it's very possible I didn't do it correctly. How's it look on your end?

**Comment by claudep** [comment]
Awesome! I triggered a build with a new PR and it ran on travis-ci.com. Thanks.

**Comment by claudep** [comment]
@notanumber, do you want to continue making releases? Otherwise, could you add me as a maintainer on Pypi (claudep)?

**Comment by notanumber** [comment]
You should have access now. I've added you as a maintainer.

**Comment by claudep** [comment]
Tag 2.1.1 created, sorry for the delay.
