### ISSUE TITLE
pypi sdist tarballs don't include tests

### ISSUE THREAD

**Issue by dvzrv** [notanumber/xapian-haystack#191]
Hi! When trying to package 2.1.1 from the pypi sdist tarball, I tried running tests, but they are not included in the tarball.
Please add them to MANIFEST.in, so distributions and anyone really can run them.

**Comment by dvzrv** [comment]
This is still a problem with 3.0.0

**Comment by claudep** [comment]
Sure, patch welcome!

**Comment by claudep** [comment]
Should be fixed in f1c3c304e. However, note that running tests is a bit complex, as a django-haystack checkout has to be done (see github workflow file for details).
