### ISSUE TITLE
Github Actions - coveralls integration needs more work

### ISSUE THREAD

**Issue by asedeno** [notanumber/xapian-haystack#205]
How xapian-haystack's tests get run confuses coveralls, and causes links to the repo / commit to not work.

Essentially, because the test process copies pieces of xapian-haystack into a checkout of django-haystack, coveralls detects the commit id from django-haystack.

Because file paths across the projects not not match, just ensuring that coveralls gets the right commit id will not fix all of the issues here.

~~I don't have a solution to this issue in mind yet.~~

Tangentially related to this, coverage does not appear to detect that `xapian_backend.py` was used when running tests, so we don't have coverage data on that.

**Comment by claudep** [comment]
I would not be so shocked if we simply drop coverage report. In any case, any new/changed feature must come with tests, so...

**Comment by asedeno** [comment]
Coverage is good, and this was bothering me. Nothing motivates me like something bugging me. 😄

**Comment by claudep** [comment]
You are awesome :smile:
