### ISSUE TITLE
'xapian_backend' has no 'XapianEngine' class

### ISSUE THREAD

**Issue by mixmastamyk** [notanumber/xapian-haystack#93]
Upgrading to Django 1.4 caused me to have to upgrade haystack, now xapian-haystack does not work.  :( ... now stuck in limbo, not sure what to do.

**Comment by TheDrifter254** [comment]
Hi I upgraded django from 1.5 to 1.7 with xapian-haystack==1.1.5b0 and django-haystack==2.0.0 but I get this error log.

    [Mon Nov 16 13:32:48.284952 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/mptt/admin.py:20: RemovedInDjango18Warning: `MPTTChangeList.get_query_set` method should be renamed `get_queryset`.
	[Mon Nov 16 13:32:48.284982 2015] [wsgi:error] [pid 692193:tid 139901570070272]   class MPTTChangeList(ChangeList):
	[Mon Nov 16 13:32:48.284986 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.286200 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/mptt/managers.py:181: RemovedInDjango18Warning: `BaseManager.get_query_set` is deprecated, use `get_queryset` instead.
	[Mon Nov 16 13:32:48.286210 2015] [wsgi:error] [pid 692193:tid 139901570070272]   return super(TreeManager, self).get_query_set().order_by(
	[Mon Nov 16 13:32:48.286213 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.287417 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ModelForm needs updating
	[Mon Nov 16 13:32:48.287427 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.287430 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.288619 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:448: RemovedInDjango18Warning: Calling modelform_factory without defining 'fields' or 'exclude' explicitly is deprecated
	[Mon Nov 16 13:32:48.288629 2015] [wsgi:error] [pid 692193:tid 139901570070272]   return django_modelform_factory(model, **kwargs)
	[Mon Nov 16 13:32:48.288633 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.288856 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form CategoryForm needs updating
	[Mon Nov 16 13:32:48.288866 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.288869 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.332878 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form AreaForm needs updating
	[Mon Nov 16 13:32:48.332900 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.332904 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.351681 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ArticleForm needs updating
	[Mon Nov 16 13:32:48.351706 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.351709 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.439540 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form BannerForm needs updating
	[Mon Nov 16 13:32:48.439567 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.439571 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.462811 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form VenueForm needs updating
	[Mon Nov 16 13:32:48.462836 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.462840 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.480725 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `VenueShowInline.queryset` method should be renamed `get_queryset`.
	[Mon Nov 16 13:32:48.480743 2015] [wsgi:error] [pid 692193:tid 139901570070272]   .__new__(mcs, name, bases, attrs))
	[Mon Nov 16 13:32:48.480747 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.480881 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `VenueShowAdmin.queryset` method should be renamed `get_queryset`.
	[Mon Nov 16 13:32:48.480890 2015] [wsgi:error] [pid 692193:tid 139901570070272]   .__new__(mcs, name, bases, attrs))
	[Mon Nov 16 13:32:48.480893 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.484525 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `EventDateInline.queryset` method should be renamed `get_queryset`.
	[Mon Nov 16 13:32:48.484536 2015] [wsgi:error] [pid 692193:tid 139901570070272]   .__new__(mcs, name, bases, attrs))
	[Mon Nov 16 13:32:48.484540 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.486701 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EventForm needs updating
	[Mon Nov 16 13:32:48.486711 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.486715 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.489560 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form RecurringEventForm needs updating
	[Mon Nov 16 13:32:48.489570 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.489574 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.526563 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form GalleryForm needs updating
	[Mon Nov 16 13:32:48.526590 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.526593 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.530743 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EntryForm needs updating
	[Mon Nov 16 13:32:48.530754 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.530757 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.549363 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form MovieForm needs updating
	[Mon Nov 16 13:32:48.549385 2015] [wsgi:error] [pid 692193:tid 139901570070272]   attrs)
	[Mon Nov 16 13:32:48.549389 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.550773 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `MovieShowInline.queryset` method should be renamed `get_queryset`.
	[Mon Nov 16 13:32:48.550784 2015] [wsgi:error] [pid 692193:tid 139901570070272]   .__new__(mcs, name, bases, attrs))
	[Mon Nov 16 13:32:48.550788 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.573542 2015] [wsgi:error] [pid 692193:tid 139901570070272] /home/kbuzz/webapps/kenyabuzz/kb/profiles/forms.py:82: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form CustomUserChangeForm needs updating
	[Mon Nov 16 13:32:48.573567 2015] [wsgi:error] [pid 692193:tid 139901570070272]   class CustomUserChangeForm(forms.ModelForm):
	[Mon Nov 16 13:32:48.573571 2015] [wsgi:error] [pid 692193:tid 139901570070272] 
	[Mon Nov 16 13:32:48.641806 2015] [wsgi:error] [pid 692193:tid 139901570070272] WSGI without exception
	[Mon Nov 16 13:32:48.685230 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439] mod_wsgi (pid=692193): Exception occurred processing WSGI script '/home/kbuzz/webapps/kenyabuzz/kb/kb/wsgi.py'.
	[Mon Nov 16 13:32:48.685273 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439] Traceback (most recent call last):
	[Mon Nov 16 13:32:48.685292 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]   File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/handlers/wsgi.py", line 175, in __call__
	[Mon Nov 16 13:32:48.685383 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]     signals.request_started.send(sender=self.__class__)
	[Mon Nov 16 13:32:48.685396 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]   File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/dispatch/dispatcher.py", line 198, in send
	[Mon Nov 16 13:32:48.685469 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]     response = receiver(signal=self, sender=sender, **named)
	[Mon Nov 16 13:32:48.685481 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]   File "/home/kbuzz/lib/python2.7/haystack/__init__.py", line 59, in reset_search_queries
	[Mon Nov 16 13:32:48.685520 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]     for conn in connections.all():
	[Mon Nov 16 13:32:48.685530 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]   File "/home/kbuzz/lib/python2.7/haystack/utils/loading.py", line 112, in all
	[Mon Nov 16 13:32:48.685597 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]     return [self[alias] for alias in self.connections_info]
	[Mon Nov 16 13:32:48.685608 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]   File "/home/kbuzz/lib/python2.7/haystack/utils/loading.py", line 100, in __getitem__
	[Mon Nov 16 13:32:48.685634 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]     self._connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
	[Mon Nov 16 13:32:48.685644 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]   File "/home/kbuzz/lib/python2.7/haystack/utils/loading.py", line 53, in load_backend
	[Mon Nov 16 13:32:48.685657 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]     return import_class(full_backend_path)
	[Mon Nov 16 13:32:48.685666 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]   File "/home/kbuzz/lib/python2.7/haystack/utils/loading.py", line 23, in import_class
	[Mon Nov 16 13:32:48.685679 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439]     raise ImportError("The Python module '%s' has no '%s' class." % (module_path, class_name))
	[Mon Nov 16 13:32:48.685695 2015] [wsgi:error] [pid 692193:tid 139901570070272] [remote 127.0.0.1:25439] ImportError: The Python module 'xapian_backend' has no 'XapianEngine' class.

**Comment by jorgecarleitao** [comment]
Xapian version in pip was completely updated for newer Django and Haystack versions. Luckily, the new version of Xapian 2.0.0 just got out. try `pip install xapian-haystack --upgrade`.
